INSERT INTO products (cd_name, artist, year, genre, photo, type)
VALUES 
('Starboy', 'The Weeknd', 2016, 'Pop', '', 'cd'),
('DAMN.', 'Kendrick Lamar', 2017, 'Hip Hop', '', 'cd'),
('Hollywood''s Bleeding', 'Post Malone', 2019, 'Pop', '', 'cd'),
('My Beautiful Dark Twisted Fantasy', 'Kanye West', 2010, 'Hip Hop', '', 'cd'),
('Evolve', 'Imagine Dragons', 2017, 'Pop Rock', '', 'cd'),
('Future Nostalgia', 'Dua Lipa', 2020, 'Pop', '', 'cd'),
('UTOPIA', 'Travis Scott', 2023, 'Hip Hop', '', 'cd'),
('El Fary Grandes exitos', 'El Fary', 1988, 'Rumba', '', 'cd'),
('Goodbye & Good Riddance', 'Juice WRLD', 2018, 'Hip-Hop', '', 'cd'),
('Trench', 'Twenty One Pilots', 2018, 'Pop', '', 'cd'),
('Favourite Worst Nightmare', 'Artic Monkeys', 2007, 'Hip-Hop', '', 'cd'),
('Stories', 'Avicii', 2015, 'Electrónica', '', 'cd'),
('Changes', 'Justin Bieber', 2020, 'Pop', '', 'cd'),
('Luv is Rage 2', 'Lil Uzi Vert', 2017, 'Hip Hop', '', 'cd'),
('Random Access Memories', 'Daft Punk', 2013, 'Electrónica', '', 'cd'),
('Flower Boy', 'Tyler, the Creator', 2019, 'Hip Hop', '', 'cd'),
('i am > i was', '21 Savage', 2018, 'Hip Hop', '', 'cd'),
('Life after death', 'The Notorius B.I.G', 1997, 'Hip Hop', '', 'cd'),
('Scary Monsters and Nice Spirites', 'Skrillex', 2010, 'Electrónica', '', 'cd'),
('The Fame', 'Lady Gaga', 2008, 'Pop', '', 'cd'),
('All Eyez on Me', '2Pac', 1996, 'Hip Hop', '', 'cd'),
('Cuéntame', 'Rosario Flores', 2009, 'Pop', '', 'cd'),
('Paradise Again', 'Swedish House Mafia', 2022, 'Electrónica', '', 'cd'),
('Diego el Cigala, Obras Maestras', 'Diego el Cigala', 2023, 'Flamenco', '', 'cd'),
('Clarity', 'Zedd', 2012, 'Electrónica', '', 'cd'),
('Man on the Moon: The end of Day', 'Kid Kudi', 2009, 'Hip Hop', '', 'cd'),
('Blonde', 'Frank Ocean', 2016, 'R&B', '', 'cd'),
('Estopa', 'Estopa', 1999, 'Pop', '', 'cd'),
('Not All Heroes Wear Capes', 'Metro Boomin', 2018, 'Hip Hop', '', 'cd'),
('Fall Out Boy', 'American Beauty / American Psycho ', 2015, 'Indie', '', 'cd');
